
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-sfagent-config
data:
  config.yaml: |-
    key: "{{ .Values.global.key }}"
    metrics:
        plugins:
        - name: postgres
          enabled: true
          interval: 30
          config:
            port: 5432
            host: localhost
            user: postgres
            password: postgres123!
            documentsTypes: []
    logging:
        plugins:
        - name: postgres-general
          enabled: true
          config:
            log_path: /var/log/postgresql/postgres*.log
            log_level:
              - error
              - warning
              - notice
              - log
