apiVersion: v1
kind: Secret
metadata:
  name: postgresql-1600353338-postgresql
  labels:
    helm.sh/chart: postgresql-0.1.0
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql-1600353338
    app.kubernetes.io/version: "9.6"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  rootPassword:  "cG9zdGdyZXM="
  multidbUserPassord: "ZGF0YWJhc2U="

