kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-1600344618
  labels:
    helm.sh/chart: postgresql-0.1.0
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql-1600344618
    app.kubernetes.io/version: "9.6"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"

